### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by miguel9554** [ghdl/ghdl-language-server#54]
My first step in trying to work with the Language Server was to install and run `ghdl-ls`. I downloaded `GHDL`, built it, then installed `ghdl-ls`, but when running it the output is the following
```
Traceback (most recent call last):
  File "/home/miguel/.local/bin/ghdl-ls", line 11, in <module>
    load_entry_point('pyghdl==1.0.dev0', 'console_scripts', 'ghdl-ls')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/miguel/.local/lib/python3.7/site-packages/vhdl_langserver/main.py", line 13, in <module>
    from . import lsp
  File "/home/miguel/.local/lib/python3.7/site-packages/vhdl_langserver/lsp.py", line 4, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```
Even running `ghdl-ls` from the docker container `ghdl/ext` (`docker run --rm -t ghdl/ext:ls-debian ghdl-ls`) gives the error

```
Traceback (most recent call last):
  File "/usr/local/bin/ghdl-ls", line 5, in <module>
    from vhdl_langserver.main import main
  File "/usr/local/lib/python3.8/site-packages/vhdl_langserver/main.py", line 13, in <module>
    from . import lsp
  File "/usr/local/lib/python3.8/site-packages/vhdl_langserver/lsp.py", line 4, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

```

**Comment by tgingold** [comment]
That should have been fixed.  Either manually install the python 'attrs' package, or pull and rebuild ghdl-ls.
